//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuruyemisService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSube
    {
        public int SubeId { get; set; }
        public string SubeAd { get; set; }
    }
}
