//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YilmazlarKuruyemis
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrunGecmisi
    {
        public int KayitId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public string UrunAd { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<int> Stok { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public Nullable<System.DateTime> DosyaTarihi { get; set; }
        public Nullable<int> SubeId { get; set; }
    }
}
